### ISSUE TITLE
ITouchAction with multiple taps keeps moving location

### ISSUE THREAD

**Issue by stcleezy** [appium/appium-dotnet-driver#101]
Driver Version 1.4.0.2, Appium 1.4.0

For example, if x = 100 and y = 100, the following will result in tapping (100,100) then (200,200).

    ITouchAction t = new TouchAction(driver)
                .Tap(x, y)
                .Wait(100)
                .Tap(x, y);
            t.Perform();

**Comment by Astro03** [comment]
In version 1.3.x.x, did this same problem exist?

**Comment by stcleezy** [comment]
Yes -- I believe I was using 1.3.0.1 before, and this worked.

**Comment by Astro03** [comment]
just troubleshooting steps since i don't have this set up right now..

1) use 1.4X with current appium - what happens?
2) use 1.3X with current appium - what happens?

if they are the same and it used to work, i bet something might have
happened on the appium server.

Just a note, we haven't touched TAP() since June 6th, 2014.

ciao,
ASTRO

**Comment by TikhomirovSergey** [comment]
It is the server side problem:
https://github.com/appium/appium/issues/5473

**Comment by stcleezy** [comment]
Yep, I updated to server version 1.4.0 (Draco) at the same time. Will close this issue.

Thanks!
