### ISSUE TITLE
Why appium work so slowly?

### ISSUE THREAD

**Issue by Radzhab** [appium/appium-dotnet-driver#102]
WHYYYYY? Doest it have good alternatives?

**Comment by TikhomirovSergey** [comment]
Hi @Radzhab 
Please describe your problem. What operation has performance problem? Which server version are you currently using? Which client version are you currently using? From which server/client version are you facing performance problems?

**Comment by Jonahss** [comment]
@Radzhab Appium is slow for several reasons, but they're all based on the fact that the underlying automation tools for Android and iOS are slow. If you look at the appium source code, it's actually a very thin client wrapped around synchronizing a dozen native processes which automate the phone.

It's also slow because of the Selenium model, where each command and response are sent over http from the test script to the device and back. While this can be the cause of perceived slowness, it's what allows the versatility to support any language, any test methodology, easy CI integration, and live repl-like automation.

If you dig deeper there are optimizations you can perform with your test setup such as using the Android Hierarchy Compression, or Instruments Without Delay on iOS.
