### ISSUE TITLE
TouchAction Perform acts differently in Java and C#

### ISSUE THREAD

**Issue by yaacovw** [appium/appium-dotnet-driver#133]
Hi,

The Perform method for TouchAction in Java binding performs a ClearParameters action. However, in the C# binding, the Clear is not performed!

As a result, if I reuse the same TouchAction variable for a second series of actions, it transmits a double action to the Appium server! Could you please fix the inconsistency?

Thanx,
yaacov weingarten
Perfecto Mobile

**Comment by Astro03** [comment]
That wasn't under my use case but is good to know.  

This is a super simple fix and will be done before next release. 

Ciao,
Astro
Sent from my phone

On Jan 19, 2016, at 01:47, Yaacov Weingarten <notifications@github.com> wrote:

Hi,

The Perform method for TouchAction in Java binding performs a ClearParameters action However, in the C# binding, the Clear is not performed!

As a result, if I reuse the same TouchAction variable for a second series of actions, it transmits a double action to the Appium server! Could you please fix the inconsistency?

Thanx,
yaacov weingarten
Perfecto Mobile

**Comment by TikhomirovSergey** [comment]
Yeah. I've toticed it. It is easy to get it fixed.

**Comment by yaacovw** [comment]
Any news on this "easy" issue?

**Comment by TikhomirovSergey** [comment]
@yaacovw 
Sorry for the late response. There is a lot of work on migration to node server 1.5.

I was trying to investigate and now I think that it is not the bug.

I "corrupted" one test a little bit. 

```с#
        [Test()]
        public void SimpleTouchActionTestCase()
        {
            IList<AppiumWebElement> els = driver.
               FindElementsByClassName("android.widget.TextView");

            int number1 = els.Count;

            TouchAction tap = new TouchAction(driver);
            tap.Tap(els[1], 10, 5, 2);
            tap.Perform();
            tap.Perform();

            els = driver.FindElementsByClassName("android.widget.TextView");

            Assert.AreNotEqual(number1, els.Count);
}
```

and it passed.
![](https://cloud.githubusercontent.com/assets/4927589/13151104/b991ce90-d679-11e5-8572-bebc50ffb9d4.png)

There is a fragment of a server output. 
https://gist.github.com/TikhomirovSergey/74493102f86fb1373ba7

As you can see it was performed twice, not three times.
[1](https://gist.github.com/TikhomirovSergey/74493102f86fb1373ba7#file-gistfile1-txt-L32)
[2](https://gist.github.com/TikhomirovSergey/74493102f86fb1373ba7#file-gistfile1-txt-L60)

Is it expected behavior? 

What about Java Client. I think the bug is on the Java Client side.

Here is a sample: 

```java
@Test
  public void MultiGestureSingleActionTest() throws InterruptedException {
    TouchAction action0 = new TouchAction(driver).tap(100,300);
    action0.perform();
    action0.perform();
  }
```

It passes too but the tapping is performed once. 
[Server output](https://gist.github.com/TikhomirovSergey/309a0e638425bb91affa)
[only single tapping](https://gist.github.com/TikhomirovSergey/74493102f86fb1373ba7#file-gistfile1-txt-L60)

If you take a look at sources ([AppiumDriver](https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/AppiumDriver.java#L323), [TouchAction](https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/TouchAction.java)) then you can find that TouchAction can't be reused now and it is needed to be built again (!!!)

So it is most likely I'll fix java client. 

@yaacovw I'm waiting for your answer. If I have described your concerns correctly then please close this issue. Please provide a use case otherwise.

**Comment by TikhomirovSergey** [comment]
Now Java client is fixed
