### ISSUE TITLE
Element.GetAttribute() does not return the attribute value, throws exception

### ISSUE THREAD

**Issue by chriscore** [appium/appium-dotnet-driver#223]
## Description

I have selected an element and am trying to get the value of an attribute. Doing this throws a NoSuchElementException: `An element could not be located on the page using the given search parameters.`

I am trying to get the value of attribute 'content-desc', which I can confirm is present, using `element.GetAttribute("content-desc");`

Appium server is responding with `result: {"status":7,"value":"This element does not have the 'content-desc' attribute"}`

Other operations in the app using Appium/selenium are generally fine.

## Environment

Appium.WebDriver 3.0.0.2
Appium server 1.8
Capabilities:
`{
  "automationName": "Appium",
  "platformName": "Android",
  "deviceName": "Android Emulator",
  "app": "C:\\Users\\chriscore\\Desktop\\YoutubeKids\\youtubeKids.apk",
  "platformVersion": "8.1.0",
  "newCommandTimeout": 6000
}`
Windows 10
Emulator: Pixel XL API v.27

## Details

Relevant application state (XML)
https://gist.github.com/chriscore/60f792a088e040d921fa396a2968f948

C# to reproduce
https://gist.github.com/chriscore/9d6289cdc57bf373e2deaf18852454bc

## Exception
https://gist.github.com/chriscore/1051284d5db6ca53c4b6008f894f4ac1

## Link to Appium logs
Targeted
https://gist.github.com/chriscore/9f04b985e23414e5d3cb93d326f15588

Full
https://gist.github.com/chriscore/d508ce4f54a408b03f159efc0667ff28

**Comment by mykola-mokhnach** [comment]
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"This element does not have the 'content-desc' attribute"}

I'd rather switch to UiAutomation2 backend. The list of available attributes there:

https://github.com/appium/appium-uiautomator2-server/blob/203cc7e57ce477f3cff5d95b135d1b3450a6033a/app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java#L81

**Comment by chriscore** [comment]
For some reason UiAutomation2 is **considerably** slower than Appium (I'd appreciate information on why that might be).

I just randomly found out that using `element.GetAttribute("name")` returns the value of content-desc (unclear why), so although it isn't clear how name is getting into there, will use that.

Thanks

**Comment by Gocoollnath** [comment]
name attribute returns content-desc value, doesn't it in appium?

**Comment by chriscore** [comment]
Yeah it seems as though it does - not sure why the attritbue names are just what they are called in the application DOM, as i would have expected to get content-desc you ask for content-desc etc

**Comment by jlipps** [comment]
The historical reason for this is that before there was any Android support in Appium, we overrode the Selenium 'find element by name' semantics with iOS 'name' semantics. Turns out on iOS that 'name' and 'accessibility id' are more or less the same, so when we instituted 'find element by accessibility id', we also allowed 'find element by name' to target the same elements. On Android, accessibility id is known as 'content-desc', which is why it's then possible to get 'content-desc' elements when searching by 'name' on Android.

**Comment by chriscore** [comment]
Ah I see. Thanks for the clarification, makes sense, cheers.

**Comment by JasonRammoray** [comment]
@jlipps, thank you for the explanation but even after reading it several times I still didn’t quite understand how to workaround the issue.
May I kindly ask you to clarify, please?

I am getting the same error as @chriscore had when running a test on SauceLab.
The thing is that the issue is not reproducible on when running on a local machine.

In my test I am just gathering a list of elements using the following XPath:
```//*[@resource-id = 'com.company.android:id/items_list’]//android.view.ViewGroup[@content-desc]```
and then map the resulting list of web elements to a list of strings by gathering `content-desc` value.

If I ran `item.getAttribute(‘content-desc’)` while being paused in a breakpoint, I get ‘ UnsupportedCommandException`.
If I send `GET` request to a webdriver hub to see details, I get status `9` with the following payload:
![image_2019_06_22T19_44_14_602Z](https://user-images.githubusercontent.com/5477500/59968840-70178a00-94f5-11e9-9179-892acf01d299.png)

The thing is, however, that this element does have `content-desc` attribute since it was found by Xpath that targets all elements having `content-desc` attribute under any parent element with `resource-id` value equal to `com.company.android:id/items_list`

I am not sure what it happens given that [getAttribute](http://appium.io/docs/en/commands/element/attributes/attribute/#response) always returns either `null` or `string`.

**Comment by jlipps** [comment]
2 questions:

1. did you try `contentDescription` as the attribute name?
2. if the error happens on sauce but not locally, I'd reach out to sauce support.

**Comment by JasonRammoray** [comment]
No, I haven't but I'll definitely try to use `contentDescription` attribute.

**Comment by JasonRammoray** [comment]
Just tried `contentDescription` but unfortunately with the same result.
I'll create a support ticket for SauceLabs support.
Thanks anyway.
