### ISSUE TITLE
Appium is not launching from visual studios.

### ISSUE THREAD

**Issue by AlphaQ1996** [appium/appium-dotnet-driver#262]
The script when run from visual studio 17 gives a error message,. please help. I've pasted the code as well as a screenshot of the error and appium doctor. 

using NUnit.Framework;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.Enums;
using OpenQA.Selenium.Remote;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppiumEAFramework
{
   [TestFixture]
    public class TestClass
    {

        [Test]
        public void OpenAppium()

        {
            DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
            desiredCapabilities.SetCapability(MobileCapabilityType.PlatformName, "Android");
            desiredCapabilities.SetCapability(MobileCapabilityType.DeviceName, "Android25");
            desiredCapabilities.SetCapability(MobileCapabilityType.App, @"C:\Users\Tester\Downloads\android-debug(3).apk");

            AndroidDriver<AndroidElement> androidDriver = new AndroidDriver<AndroidElement>(desiredCapabilities);
        }
    } 
}
![1](https://user-images.githubusercontent.com/29882370/46060727-df886500-c181-11e8-9b48-6d9d600b2082.PNG)
![capture](https://user-images.githubusercontent.com/29882370/46060731-e020fb80-c181-11e8-891d-22e5196a15b9.PNG)

**Comment by akinsolb** [comment]
Where have you obtained the appium.Webdriver and selenium.webdriver DLL from?

**Comment by AlphaQ1996** [comment]
I used Nuget package manager to install them on visual studios.

**Comment by AlphaQ1996** [comment]
I've downloaded it but how to install it to the solution?

Nathan Moniz

**Comment by akinsolb** [comment]
When I say download into your solution, I'm referring to the same process you used to install the nuget packages in the first place. You'd have to open the Nuget manager for your project or solution, select appium.webdriver and select the version 3.0.0.2. Let me know if this is convoluted, and I'll send a screenshot if necessary. I believe you currently have the nuget versions installed: Appium.Webdriver v3.0.0.2 and Selenium.WebDriver v3.14, but I can't confirm because you haven't stated. If you change the version of Selenium to 3.8 (the stable and supported Selenium version for appium), you should be good to go

**Comment by AlphaQ1996** [comment]
It stared working.Thanks so much. I've been struggling with this for 2 days.
