### ISSUE TITLE
Csharp test solutions not going through

### ISSUE THREAD

**Issue by eliassal** [appium/appium-dotnet-driver#279]
**The problem**
I downloaded the samples zip, opened the test.sln in visual studio 2017, updated nuget packages, projects compile, running any test, I get the following message:
[10/26/2018 7:08:25 PM Informational] Test project test does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
[10/26/2018 7:08:25 PM Informational] ========== Run test finished: 0 run (0:00:01.7409422) ==========
**Environment**
Win 10 64bit, VS 2K17, .Net Framework 4.6.1
Just installe Appium with npm
win 10 64 bit:
Node.js version v6.12.3
**Details**
Tests cannot execute missing nuget test adapters

**Comment by eliassal** [comment]
I downloaded the zip file from
https://github.com/appium/appium > 
appium/sample-code/csharp/test

**Comment by eliassal** [comment]
Now I added a reference to

> Microsoft.VisualStudio.TestPlatform.TestFramework


Run any test nothing happens, just get

> [10/27/2018 1:16:10 PM Informational] ------ Run test started ------
> [10/27/2018 1:16:10 PM Informational] ========== Run test finished: 0 run (0:00:00.4400338) ==========

**Comment by akinsolb** [comment]
Then your issue doesn't belong in this repository. It should be raised in [that](https://github.com/appium/appium) repo. 
If your'e looking for samples for dotnet. Its probably best for you to clone this repo and look at the integration tests

**Comment by eliassal** [comment]
I initially reported this in the repo you are mentioning and Mykola Mokhnach responded that it needs to be reported here and closed the issue
https://github.com/appium/appium/issues/11584#event-1929823737

**Comment by akinsolb** [comment]
@eliassal The solution you are referring to is outdated, and you probably followed documentation which led you there in the first place. Maintenance and ensuring the sample project is an issue but not a bug against the appium codebase. That solution is referencing a version of Appium where vast amount of changes have been made since. Once the next major release is out, I'll look to update the project to a hopefully working version of the client.

I'll have a look into the solution when I get a chance, as It sounds like it is missing a test adapter. 
Regardless, you can either fork this repository or get a beta release version from [nuget.org](https://www.nuget.org/packages/Appium.WebDriver/), and take the advice I provided in my previous comment. If you happen to find an issue, please raise a bug that is relevant to code in this repository using the usual issue template.
