### ISSUE TITLE
Cannot send specific ChromeOptions with AppiumOptions

### ISSUE THREAD

**Issue by alexlazarciuc** [appium/appium-dotnet-driver#304]
## Description

Hi,

I'm running some web tests on mobile devices in Browserstack. The tests are executed on native mobile browser - Chrome. 
At a specific flow of the test I'm filling in a payment form, once that happens, Chrome will display a pop up to save the Credit Card details at the bottom of the page and this is covering the button I try to click. 

![screenshot_62](https://user-images.githubusercontent.com/10537190/50633578-bc6d0e80-0f43-11e9-8295-2618ba143852.png)

Browsing the internet I've discovered that you can disable that pop up for Chrome on desktop with ChromeOptions: https://sqa.stackexchange.com/questions/26275/how-to-disable-chrome-save-your-password-selenium-java/26427

So, I've tried to do the same for my mobile optimized tests, but because the driver options are appium type, Appium Options does not have the support to include that capability called AddUserProfilePreference().

Do you guys know by any chance if there's a way to achieve what I'm trying to do? To attach Chrome specific options when running the browser on a mobile device?

**Comment by saikrishna321** [comment]
@alexlazarciuc 

FYI: this example is java-client, not sure on how we do it in dot-net 

@akinsolb 

DesiredCapabilities desired_capabilities = new DesiredCapabilities();
ChromeOptions chrome_options = new ChromeOptions();
	chrome_options.setExperimentalOption("androidProcess", "com.tencent.mm:tools");
	desired_capabilities.setCapability(ChromeOptions.CAPABILITY, chrome_options);
	desired_capabilities.setCapability(AndroidMobileCapabilityType.PLATFORM, "Android");
	desired_capabilities.setCapability(AndroidMobileCapabilityType.VERSION, "6.0");
	desired_capabilities.setCapability("deviceName", "Android");
	desired_capabilities.setCapability(MobileCapabilityType.FORCE_MJSONWP, true);
        desired_capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"chrome");
	desired_capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
	
	
	
	try {
		driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),desired_capabilities);
	} catch (MalformedURLException e) {
		e.printStackTrace();
	}
	

}

**Comment by alexlazarciuc** [comment]
Hey @saikrishna321 

Your example would work perfectly fine with another version of Selenium, the selenium version we use is 3.14.0 which no longer support DesiredCapabilities and for each type of Browser / Platform you have to set the desired option, example - ChromeOptions or AppiumOptions.

See this post by @jimevans 
https://github.com/appium/appium-dotnet-driver/pull/258#issuecomment-421757592

Thanks

**Comment by jimevans** [comment]
@alexlazarciuc It’s possible to replicate the JSON payload that is generated by the Java code above using `ChromeOptions` (assuming the capability names are not conflicting with known capability names). Here’s what that would look like:

    ChromeOptions options = new ChromeOptions();
    options.AddAdditionalCapability("androidProcess", "com.tencent.mm:tools");
    options.AddAdditionalCapability(AndroidMobileCapabilityType.PLATFORM, "Android", true);
    options.AddAdditionalCapability(AndroidMobileCapabilityType.VERSION, "6.0", true);
    options.AddAdditionalCapability("deviceName", "Android", true);
    options.AddAdditionalCapability(MobileCapabilityType.FORCE_MJSONWP, true, true);
    options.AddAdditionalCapability(MobileCapabilityType.BROWSER_NAME,"chrome", true);
    options.AddAdditionalCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2", true);
    ICapabilities caps = options.ToCapabilities();

Will that work with Appium? No idea, but it should generate the same (or functionally equivalent) JSON payload for use with the new session command. Note that the API is likely to change somewhat in 4.0, but will remain substantially similar.

**Comment by akinsolb** [comment]
That should work

**Comment by alexlazarciuc** [comment]
@jimevans 

Thanks, I have a one major issue with that tho. So, because we are testing on a mobile device via BrowserStack, we use AppiumOptions as DriverOptions and "trying" to pass chromeOptions into it as capability(via AddAdditionalCapability). by using ChromeOptions.Capability which resolves to "goog:chromeOptions" as BrowserStack is running Selenium 3,14. The AppiumOptions(in version 4.0.0.4-beta) does not accept that and rather forcing us to send it in the older name which is just "chromeOptions" which is not correctly parsed by BrowserStack, any thoughts?

**Comment by jimevans** [comment]
@alexlazarciuc I’m afraid I cannot speak to why BrowserStack or Appium is allowing the use of capabilities that are not compliant with the protocol defined by the W3C WebDriver Specification. You might be able to get away with using “chromeOptions” as the capability name in `AddAdditionalCapability`. I don’t have any idea what JSON payload is expected in the combination of Appium and BrowserStack.

Look, there’s nothing preventing you from using `DesiredCapabilities` when using Selenium 3.x. Yes, you’ll get a compile warning because the class is deprecated, but that’s all it is: a warning. I would expect that to change in the 4.x timeframe for Selenium, but for now, it would be fine.

I am not an Appium .NET bindings user, nor am I a BrowserStack customer. I cannot knowledgeably comment on the expectations of their libraries. I _am_ responsible for the maintenance of the .NET bindings for Selenium, and am part of the working group responsible for the specification. I _do_ have strongly held opinions about the incredibly flawed nature of the API design of `DesiredCapabilities` in .NET. I am partly responsible for that flawed and inelegant design, and have been trying to correct it ever since. I am unwilling to compromise my efforts to improve and simplify both the Selenium .NET API and its implementation in the Selenium project.

I would welcome the opportunity to consult with either the Appium .NET maintainers or BrowserStack about the API design and the JSON payload generated by those classes.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-dotnet-driver/issues/304#issuecomment-451410731
ah, https://github.com/appium/appium-dotnet-driver/blob/96d945c754559e4cb65acaba90ae4e15f2fd2d9b/src/Appium.Net/Appium/Enums/AndroidMobileCapabilityType.cs#L193-L197 hardcode `chromeOptions`. Appium accepts `chromeOptions`, `goog:chromeOptions` and `appium:chromeOptions`. So, we can modify there as a quick hot fix.

**Comment by akinsolb** [comment]
> @jimevans
> 
> Thanks, I have a one major issue with that tho. So, because we are testing on a mobile device via BrowserStack, we use AppiumOptions as DriverOptions and "trying" to pass chromeOptions into it as capability(via AddAdditionalCapability). by using ChromeOptions.Capability which resolves to "goog:chromeOptions" as BrowserStack is running Selenium 3,14. The AppiumOptions(in version 4.0.0.4-beta) does not accept that and rather forcing us to send it in the older name which is just "chromeOptions" which is not correctly parsed by BrowserStack, any thoughts?

@alexlazarciuc can you post the code to reproduce this? If you are passing an instance of ChromeOptions to AppiumOptions like so: 
`SetAdditionalCapability(ChromeOptions.Capability, chromeOptionInstance)` 
the client shouldn't be sending "chromeOptions" in v4.0.0.4-beta because it contains Selenium 3.14.
