### ISSUE TITLE
AppiumOptions.ToDictionary() throws StackOverflowException

### ISSUE THREAD

**Issue by Exoow** [appium/appium-dotnet-driver#338]
## Description

Create an AppiumOptions object and add some options.
Call ToDictionary() on this object. The code exits with a StackOverflowException.

## Environment

* Latest Appium beta (4.0.0.6)

## Code To Reproduce Issue [ Good To Have ]

AppiumOptions options = new AppiumOptions();
            options.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            options.AddAdditionalCapability(MobileCapabilityType.DeviceName, "9886785356548358"); 
            options.AddAdditionalCapability(MobileCapabilityType.AutomationName, "UiAutomator2"); 
            options.AddAdditionalCapability("appPackage", "com.test.acc");
            options.AddAdditionalCapability("appActivity", "com.test.acc.MainActivity");
            options.AddAdditionalCapability("chromedriverExecutableDir", Environment.CurrentDirectory);
var caps = options.ToDictionary();

**Comment by etadzeta** [comment]
Looks like `AppiumOptions.ToDictionary()` just calls `AppiumCapabilities.ToDictionary()` method.

In AppiumCapabilities:
````C#
public Dictionary<string, object> ToDictionary() {
    return this.ToDictionary();
}
````
So it just calls itself infinitely, that's why you face `StackOverflowException`

`DesiredCapabilities` class has its internal [dictionary](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/DesiredCapabilities.cs):
````C#
private readonly Dictionary<string, object> capabilities = new Dictionary<string, object>();
````
But  `DesiredCapabilities` class does not provide `ToDictionary()` method at all.

I guess it can only be accessed with reflection, e.g:
````C#
public class AppiumCapabilities : DesiredCapabilities {
    public Dictionary<string, object> ToDictionary() {
        FieldInfo capsField = typeof(DesiredCapabilities)
                    .GetField("capabilities", BindingFlags.Instance | BindingFlags.NonPublic);
        return capsField?.GetValue(this) as Dictionary<string, object>;
    }
}
````
I don't think it's a good idea to get a private field in such way, it's just not exposed.

@akinsolb what do you think about it?

**Comment by akinsolb** [comment]
@etadzeta Yeah this function shouldn't be available. the ideal solution would be to have an Option class for each driver, and reduce reflection, which will probably erase the need for  AppiumCapabilities.

If a user wants to verify a capability, they can use: 
`HasCapability(string capability)` method on the ICapabilities interface

**Comment by akinsolb** [comment]
@etadzeta we could probably put this in until Option classes are implemented?

**Comment by etadzeta** [comment]
@akinsolb do you mean to use that approach with reflection? And once Option classes are implemented - get rid of AppiumCapabilities?

**Comment by akinsolb** [comment]
Yes, that is exactly what I meant
