### ISSUE TITLE
Add Is Keyboard Shown endpoint

### ISSUE THREAD

**Issue by akinsolb** [appium/appium-dotnet-driver#364]
## Description
Add Is Keyboard Shown endpoint to determine whether or not the soft keyboard is shown

## Endpoint Documentation
http://appium.io/docs/en/commands/device/keys/is-keyboard-shown/

**Comment by sanjaykumar5115** [comment]
hi,

 I want to do this task what is process to complete it

**Comment by akinsolb** [comment]
@sanjaykumar5115 fork the repository, create a branch, implement the API + fulfilling the requirements of the PR template, raise the PR of your forked branch with the API enhancement, It gets reviewed, after approval, it gets merged

**Comment by sanjaykumar5115** [comment]
Hi laoluCan you describe the entire process in details or share the document so that i can take the help from it.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Laolu Benson <notifications@github.com> Date: 12/9/19  17:14  (GMT+05:30) To: appium/appium-dotnet-driver <appium-dotnet-driver@noreply.github.com> Cc: Sanjay kumar <sanjaykumar5115@Gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [appium/appium-dotnet-driver] Add Is Keyboard Shown endpoint
  (#364) @sanjaykumar5115 fork the repository, create a branch, implement the API + fulfilling the requirements of the PR template, raise the PR of your forked branch with the API enhancement, It gets reviewed, after approval, it gets merged

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/appium/appium-dotnet-driver/issues/364?email_source=notifications\u0026email_token=ABH4ZGJFQSWAOVRYUL6HXKLQXYVSNA5CNFSM4JIUHOIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGI33SA#issuecomment-563199432",
"url": "https://github.com/appium/appium-dotnet-driver/issues/364?email_source=notifications\u0026email_token=ABH4ZGJFQSWAOVRYUL6HXKLQXYVSNA5CNFSM4JIUHOIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGI33SA#issuecomment-563199432",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
