### ISSUE TITLE
Where is the ToggleWifi and ToggleAirplaneMode going?

### ISSUE THREAD

**Issue by EthanJiang** [appium/appium-dotnet-driver#78]
In the latest version 1.2.0.8. I can't find the ToggleWifi and ToggleAirplaneMode. but the ToggleLocationServices is still there.

Do you change the way how to use it?
Is there anyone can explain this?

**Comment by EthanJiang** [comment]
It seems that those two functions has been removed. and the ConnectionType become a property.

**Comment by Astro03** [comment]
@EthanJiang  I feel like the ogling of the airplane mode should still be in there. if it got removed, maybe it was by accident.  I'll take a look at this on thursday. cheers

**Comment by EthanJiang** [comment]
Thanks.

**Comment by Astro03** [comment]
@EthanJiang I'm presuming you are working with ios or appium driver. The connection type is no longer there since it's not supported by all devices. If you want to use connection type, you need to have a android driver instantiated.  This article https://discuss.appium.io/t/ruby-ios-can-we-toggle-flight-mode-in-ios/2454/4  states that it's an ios restriction (sorry couldn't find the actual docs).

**Comment by EthanJiang** [comment]
ok. thanks.
